package Main;

import Queries.ClassQueries;
import Queries.CourseQueries;
import Queries.MultiTableQueries;
import Queries.ScheduleQueries;
import Queries.SemesterQueries;
import Queries.StudentQueries;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Base64;
import java.util.Calendar;
import java.util.List;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import Entry.ClassDescription;
import Entry.ClassEntry;
import Entry.CourseEntry;
import Entry.ScheduleEntry;
import Entry.StudentEntry;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author daksh
 */
public class MainFrame extends javax.swing.JFrame {

        /**
         * Creates new form MainFrame
         */
        private String currentSemester;
        private String author;
        private String project;

        public MainFrame() {
                initComponents();
                checkData();
                rebuildSemesterComboBoxes();

                if (currentSemesterComboBox.getSelectedItem() != null) {
                        updateAllComponents();
                }
        }

        public void rebuildSemesterComboBoxes() {
                ArrayList<String> semesters = SemesterQueries.getSemesterList();
                currentSemesterComboBox.setModel(new javax.swing.DefaultComboBoxModel(semesters.toArray()));
                if (semesters.size() > 0) {
                        currentSemesterLabel.setText(semesters.get(0));
                        currentSemester = semesters.get(0);
                } else {
                        currentSemesterLabel.setText("None, add a semester.");
                        currentSemester = "None";
                }
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        addSemesterTextfield = new javax.swing.JTextField();
        addSemesterSubmitButton = new javax.swing.JButton();
        addSemesterStatusLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        courseCourseCodeLabel = new javax.swing.JLabel();
        courseDescLabel = new javax.swing.JLabel();
        courseCodeText = new javax.swing.JTextField();
        courseDescText = new javax.swing.JTextField();
        addCourseButton = new javax.swing.JButton();
        addSemesterStatusLabel1 = new javax.swing.JLabel();
        addCourseStatusLabel = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        addStudentButton = new javax.swing.JButton();
        studentIDLabel = new javax.swing.JLabel();
        studentIDText = new javax.swing.JTextField();
        firstNameLabel = new javax.swing.JLabel();
        firstNameText = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        lastNameText = new javax.swing.JTextField();
        addStudentStatusLabel = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        selectDisplayClassCheckBox = new javax.swing.JComboBox<>();
        selectDisplayClassLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        displayScheduleWaitlistedTable = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        displayScheduleStudentTable = new javax.swing.JTable();
        waitlistedStudentsTableLabel = new javax.swing.JLabel();
        scheduledStudentsTableLabel = new javax.swing.JLabel();
        displayClassesListButton = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        deleteStudentLabel = new javax.swing.JLabel();
        deleteStudentComboBox = new javax.swing.JComboBox<>();
        deleteStudentButton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        deleteStudentStatusText = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel12 = new javax.swing.JPanel();
        dropAdminClassButton = new javax.swing.JButton();
        dropAdminClassComboBox = new javax.swing.JComboBox<>();
        dropAdminClassLabel = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        dropAdminClassLabelStatusText = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        addClassButton = new javax.swing.JButton();
        classCourseCodeLabel = new javax.swing.JLabel();
        courseCodeComboBox = new javax.swing.JComboBox<>();
        seatLabel = new javax.swing.JLabel();
        seatSpinner = new javax.swing.JSpinner();
        addClassStatusLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayClassTable = new javax.swing.JTable();
        updateClassesTable = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        selectClassLabel = new javax.swing.JLabel();
        selectClassComboBox = new javax.swing.JComboBox<>();
        selectStudentLabel = new javax.swing.JLabel();
        selectStudentComboBox = new javax.swing.JComboBox<>();
        addScheduleClassesButton = new javax.swing.JButton();
        scheduleClassesStatusLabel = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        selectClassLabel1 = new javax.swing.JLabel();
        selectDisplayStudentCheckBox = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        displayScheduleTable = new javax.swing.JTable();
        updateScheduleTableButton = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        dropStudentClassStatusTextBox = new javax.swing.JTextArea();
        dropStudentClassButton = new javax.swing.JButton();
        dropStudentClassComboBox = new javax.swing.JComboBox<>();
        dropStudentClassLabel = new javax.swing.JLabel();
        dropStudentStudentLabel = new javax.swing.JLabel();
        dropStudentClassStudentComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        currentSemesterLabel = new javax.swing.JLabel();
        currentSemesterComboBox = new javax.swing.JComboBox<>();
        changeSemesterButton = new javax.swing.JButton();
        aboutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Course Scheduler");

        jLabel3.setText("Semester Name:");

        addSemesterTextfield.setColumns(20);

        addSemesterSubmitButton.setText("Submit");
        addSemesterSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSemesterSubmitButtonActionPerformed(evt);
            }
        });

        addSemesterStatusLabel.setText("                                                   ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addSemesterTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(addSemesterSubmitButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addSemesterStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(addSemesterTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addSemesterSubmitButton)
                .addGap(18, 18, 18)
                .addComponent(addSemesterStatusLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Add Semester", jPanel3);

        courseCourseCodeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        courseCourseCodeLabel.setText("Course Code:");

        courseDescLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        courseDescLabel.setText("Course Description:");

        courseCodeText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        courseCodeText.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        courseCodeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseCodeTextActionPerformed(evt);
            }
        });

        courseDescText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        courseDescText.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        courseDescText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseDescTextActionPerformed(evt);
            }
        });

        addCourseButton.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        addCourseButton.setText("Confrim");
        addCourseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCourseButtonActionPerformed(evt);
            }
        });

        addSemesterStatusLabel1.setText("                                                   ");

        addCourseStatusLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addCourseStatusLabel.setText("                                                   ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(addCourseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addCourseStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(courseDescLabel)
                            .addComponent(courseCourseCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(courseDescText)
                            .addComponent(courseCodeText, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(194, 194, 194)
                    .addComponent(addSemesterStatusLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(206, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseCourseCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(courseCodeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(courseDescLabel)
                    .addComponent(courseDescText, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addCourseButton, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(addCourseStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(126, 126, 126)
                    .addComponent(addSemesterStatusLabel1)
                    .addContainerGap(127, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab("Add Course", jPanel4);

        addStudentButton.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        addStudentButton.setText("Add");
        addStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentButtonActionPerformed(evt);
            }
        });

        studentIDLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        studentIDLabel.setText("Student ID:");

        studentIDText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        studentIDText.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        studentIDText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentIDTextActionPerformed(evt);
            }
        });

        firstNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        firstNameLabel.setText("First Name:");

        firstNameText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        firstNameText.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        firstNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextActionPerformed(evt);
            }
        });

        lastNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lastNameLabel.setText("Last Name:");

        lastNameText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lastNameText.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        lastNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTextActionPerformed(evt);
            }
        });

        addStudentStatusLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addStudentStatusLabel.setText("                                                   ");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(addStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(addStudentStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addComponent(lastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lastNameText))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                            .addComponent(firstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(firstNameText))
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addComponent(studentIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(studentIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(studentIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(studentIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addStudentButton)
                    .addComponent(addStudentStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        jTabbedPane2.addTab("Add Student", jPanel7);

        selectDisplayClassCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectDisplayClassCheckBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        selectDisplayClassCheckBox.setPreferredSize(new java.awt.Dimension(72, 32));
        selectDisplayClassCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectDisplayClassCheckBoxActionPerformed(evt);
            }
        });

        selectDisplayClassLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectDisplayClassLabel.setText("Select Class:");

        displayScheduleWaitlistedTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Last Name", "First Name", "StudentID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(displayScheduleWaitlistedTable);

        displayScheduleStudentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Last Name", "First Name", "StudentID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(displayScheduleStudentTable);

        waitlistedStudentsTableLabel.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        waitlistedStudentsTableLabel.setText("Waitlisted Students");

        scheduledStudentsTableLabel.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        scheduledStudentsTableLabel.setText("Scheduled Students");

        displayClassesListButton.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        displayClassesListButton.setText("Display");
        displayClassesListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayClassesListButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(selectDisplayClassLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectDisplayClassCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(displayClassesListButton))
                    .addComponent(scheduledStudentsTableLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(waitlistedStudentsTableLabel)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectDisplayClassLabel)
                    .addComponent(selectDisplayClassCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displayClassesListButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(waitlistedStudentsTableLabel)
                    .addComponent(scheduledStudentsTableLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Display Class", jPanel10);

        deleteStudentLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deleteStudentLabel.setText("Select Student:");

        deleteStudentComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deleteStudentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        deleteStudentComboBox.setPreferredSize(new java.awt.Dimension(72, 32));

        deleteStudentButton.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        deleteStudentButton.setText("Delete");
        deleteStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteStudentButtonActionPerformed(evt);
            }
        });

        deleteStudentStatusText.setEditable(false);
        deleteStudentStatusText.setColumns(20);
        deleteStudentStatusText.setRows(5);
        jScrollPane5.setViewportView(deleteStudentStatusText);

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane6.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane5)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(deleteStudentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteStudentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteStudentButton))
                    .addComponent(jScrollPane6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteStudentLabel)
                    .addComponent(deleteStudentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteStudentButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Drop Student", jPanel11);

        dropAdminClassButton.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        dropAdminClassButton.setText("Delete");
        dropAdminClassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropAdminClassButtonActionPerformed(evt);
            }
        });

        dropAdminClassComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dropAdminClassComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        dropAdminClassComboBox.setPreferredSize(new java.awt.Dimension(72, 32));
        dropAdminClassComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropAdminClassComboBoxActionPerformed(evt);
            }
        });

        dropAdminClassLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dropAdminClassLabel.setText("Select Class:");

        dropAdminClassLabelStatusText.setEditable(false);
        dropAdminClassLabelStatusText.setColumns(20);
        dropAdminClassLabelStatusText.setRows(5);
        jScrollPane7.setViewportView(dropAdminClassLabelStatusText);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(dropAdminClassLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dropAdminClassComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dropAdminClassButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dropAdminClassLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dropAdminClassComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dropAdminClassButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jTabbedPane2.addTab("Drop Class", jPanel12);

        addClassButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addClassButton.setText("Confirm");
        addClassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClassButtonActionPerformed(evt);
            }
        });

        classCourseCodeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        classCourseCodeLabel.setText("Course Code:");

        courseCodeComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        courseCodeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        courseCodeComboBox.setPreferredSize(new java.awt.Dimension(72, 32));

        seatLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        seatLabel.setText("Seat:");

        seatSpinner.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        seatSpinner.setPreferredSize(new java.awt.Dimension(64, 32));

        addClassStatusLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addClassStatusLabel.setText("                                                   ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(seatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addClassButton, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(classCourseCodeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(addClassStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(courseCodeComboBox, 0, 107, Short.MAX_VALUE)
                            .addComponent(seatSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(classCourseCodeLabel)
                    .addComponent(courseCodeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(seatSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(addClassButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(addClassStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );

        jTabbedPane2.addTab("Add Class", jPanel6);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Admin", jPanel1);

        jTabbedPane3.setPreferredSize(new java.awt.Dimension(730, 335));

        displayClassTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Course Code", "Description", "Seats"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(displayClassTable);

        updateClassesTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        updateClassesTable.setText("Update");
        updateClassesTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateClassesTableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateClassesTable)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateClassesTable)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Display Classes", jPanel5);

        selectClassLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectClassLabel.setText("Select Classes:");

        selectClassComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectClassComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        selectClassComboBox.setPreferredSize(new java.awt.Dimension(72, 32));

        selectStudentLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectStudentLabel.setText("Select Student:");

        selectStudentComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectStudentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        selectStudentComboBox.setPreferredSize(new java.awt.Dimension(72, 32));

        addScheduleClassesButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addScheduleClassesButton.setText("Add to Schedule");
        addScheduleClassesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addScheduleClassesButtonActionPerformed(evt);
            }
        });

        scheduleClassesStatusLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        scheduleClassesStatusLabel.setText("                                                   ");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(selectStudentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                        .addComponent(selectClassLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(addScheduleClassesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scheduleClassesStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(selectClassComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(selectStudentComboBox, 0, 178, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectClassLabel)
                    .addComponent(selectClassComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectStudentLabel)
                    .addComponent(selectStudentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addScheduleClassesButton, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(scheduleClassesStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(91, 91, 91))
        );

        jTabbedPane3.addTab("Schedule Classes", jPanel9);

        selectClassLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectClassLabel1.setText("Select Student:");

        selectDisplayStudentCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectDisplayStudentCheckBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        selectDisplayStudentCheckBox.setPreferredSize(new java.awt.Dimension(72, 32));

        displayScheduleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Course Code", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(displayScheduleTable);

        updateScheduleTableButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        updateScheduleTableButton.setText("Update Classes Table");
        updateScheduleTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateScheduleTableButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(updateScheduleTableButton)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(selectClassLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(selectDisplayStudentCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectClassLabel1)
                    .addComponent(selectDisplayStudentCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(updateScheduleTableButton)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Display Schedule", jPanel8);

        dropStudentClassStatusTextBox.setEditable(false);
        dropStudentClassStatusTextBox.setColumns(20);
        dropStudentClassStatusTextBox.setRows(5);
        jScrollPane8.setViewportView(dropStudentClassStatusTextBox);

        dropStudentClassButton.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        dropStudentClassButton.setText("Delete");
        dropStudentClassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropStudentClassButtonActionPerformed(evt);
            }
        });

        dropStudentClassComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dropStudentClassComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        dropStudentClassComboBox.setPreferredSize(new java.awt.Dimension(72, 32));
        dropStudentClassComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropStudentClassComboBoxActionPerformed(evt);
            }
        });

        dropStudentClassLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dropStudentClassLabel.setText("Select Class:");

        dropStudentStudentLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dropStudentStudentLabel.setText("Select Student:");

        dropStudentClassStudentComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dropStudentClassStudentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        dropStudentClassStudentComboBox.setPreferredSize(new java.awt.Dimension(72, 32));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jScrollPane8)
                        .addContainerGap())
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(dropStudentClassLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dropStudentClassComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dropStudentStudentLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dropStudentClassStudentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dropStudentClassButton, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                        .addGap(21, 21, 21))))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dropStudentClassLabel)
                    .addComponent(dropStudentClassComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dropStudentClassButton)
                    .addComponent(dropStudentStudentLabel)
                    .addComponent(dropStudentClassStudentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Drop Class", jPanel13);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
                .addGap(31, 31, 31))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Student", jPanel2);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        jLabel2.setText("Current Semester: ");

        currentSemesterLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        currentSemesterLabel.setText("           ");

        currentSemesterComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        changeSemesterButton.setText("Change Semester");
        changeSemesterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeSemesterButtonActionPerformed(evt);
            }
        });

        aboutButton.setText("About");
        aboutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(currentSemesterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(currentSemesterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(changeSemesterButton)
                                .addGap(31, 31, 31)
                                .addComponent(aboutButton)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(currentSemesterLabel)
                    .addComponent(currentSemesterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeSemesterButton)
                    .addComponent(aboutButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void dropAdminClassButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_dropAdminClassButtonActionPerformed
                // TODO add your handling code here:
                String statusLog = "";
                String semester = (String) currentSemesterComboBox.getSelectedItem();
                String courseCode = (String) dropAdminClassComboBox.getSelectedItem();

                ClassQueries.dropClass(semester, courseCode);

                statusLog += "Scheduled students dropped from the course:\n";
                ArrayList<ScheduleEntry> scheduledStudenetDeletedClass = ScheduleQueries
                                .getScheduledStudentsByClass(semester, courseCode);
                for (ScheduleEntry scheduleEntry : scheduledStudenetDeletedClass) {
                        StudentEntry student = StudentQueries.getStudent(scheduleEntry.getStudentID());
                        statusLog += String.format("%s,%s %s\n", student.getLastName(), student.getFirstName(),
                                        student.getStudentID());
                }

                statusLog += "\nWaitlisted students dropped from the course:\n";
                ArrayList<ScheduleEntry> waitlistedStudenetDeletedClass = ScheduleQueries
                                .getWaitlistedStudentsByClass(semester, courseCode);
                for (ScheduleEntry scheduleEntry : waitlistedStudenetDeletedClass) {
                        StudentEntry student = StudentQueries.getStudent(scheduleEntry.getStudentID());
                        statusLog += String.format("%s,%s %s\n", student.getLastName(), student.getFirstName(),
                                        student.getStudentID());
                }

                ScheduleQueries.dropScheduleByCourse(semester, courseCode);
                dropAdminClassLabelStatusText.setText(statusLog);
                updateSelectClassComboBox();

        }// GEN-LAST:event_dropAdminClassButtonActionPerformed

        private void dropAdminClassComboBoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_dropAdminClassComboBoxActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_dropAdminClassComboBoxActionPerformed

        private void dropStudentClassButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_dropStudentClassButtonActionPerformed
                // TODO add your handling code here:
                String statusLog = "";
                String semester = (String) currentSemesterComboBox.getSelectedItem();
                String courseCode = (String) dropStudentClassComboBox.getSelectedItem();
                String studentID = StudentQueries
                                .getStudentID(((String) dropStudentClassStudentComboBox.getSelectedItem()));

                ScheduleQueries.dropStudentScheduleByCourse(semester, studentID, courseCode);
                StudentEntry student = StudentQueries.getStudent(studentID);
                statusLog += String.format("%s, %s %s has been dropped from %s\n",
                                student.getLastName(),
                                student.getFirstName(), student.getStudentID(),
                                courseCode);

                int scheduledStudentCount = ScheduleQueries.getScheduledStudentCount(semester, courseCode);
                int seats = ClassQueries.getClassSeats(semester, courseCode);
                if (seats > scheduledStudentCount) {
                        ArrayList<ScheduleEntry> allWaitlistClass = ScheduleQueries
                                        .getWaitlistedStudentsByClass(semester,
                                                        courseCode);
                        if (!allWaitlistClass.isEmpty()) {
                                ScheduleQueries.updateScheduleEntry(allWaitlistClass.get(0));
                                StudentEntry studentWait = StudentQueries
                                                .getStudent(allWaitlistClass.get(0).getStudentID());
                                statusLog += String.format("%s, %s %s has been scheduled into %s\n",
                                                studentWait.getLastName(),
                                                studentWait.getFirstName(), studentWait.getStudentID(),
                                                allWaitlistClass.get(0).getCourseCode());
                        }
                }

                dropStudentClassStatusTextBox.setText(statusLog);

        }// GEN-LAST:event_dropStudentClassButtonActionPerformed

        private void dropStudentClassComboBoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_dropStudentClassComboBoxActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_dropStudentClassComboBoxActionPerformed

        private void deleteStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_deleteStudentButtonActionPerformed
                // TODO add your handling code here:
                String statusLog = "";
                String studentID = StudentQueries.getStudentID(((String) deleteStudentComboBox.getSelectedItem()));

                StudentQueries.dropStudent(studentID);
                statusLog = String.format("%s %s has been dropped from the list of students\n",
                                (String) deleteStudentComboBox.getSelectedItem(), studentID);

                for (String semester : SemesterQueries.getSemesterList()) {
                        statusLog += String.format("\nFor Semester: %s\n", semester);
                        ArrayList<ScheduleEntry> deletedStudentSchedule = ScheduleQueries.getScheduleByStudent(semester,
                                        studentID);
                        for (ScheduleEntry scheduleEntry : deletedStudentSchedule) {
                                String courseCode = scheduleEntry.getCourseCode();

                                if (ScheduleQueries.isStudentWaitlisted(semester, studentID, courseCode)) {
                                        statusLog += String.format("%s %s has been dropped from the waitlist for %s\n",
                                                        (String) deleteStudentComboBox.getSelectedItem(), studentID,
                                                        courseCode);
                                } else {
                                        statusLog += String.format("%s %s has been dropped from %s\n",
                                                        (String) deleteStudentComboBox.getSelectedItem(), studentID,
                                                        courseCode);
                                }
                                ;
                                ScheduleQueries.dropStudentScheduleByCourse(semester, studentID, courseCode);

                                int scheduledStudentCount = ScheduleQueries.getScheduledStudentCount(semester,
                                                courseCode);

                                int seats = ClassQueries.getClassSeats(semester, courseCode);
                                if (seats > scheduledStudentCount) {
                                        ArrayList<ScheduleEntry> allWaitlistClass = ScheduleQueries
                                                        .getWaitlistedStudentsByClass(semester,
                                                                        courseCode);
                                        if (!allWaitlistClass.isEmpty()) {
                                                ScheduleQueries.updateScheduleEntry(allWaitlistClass.get(0));
                                                StudentEntry student = StudentQueries
                                                                .getStudent(allWaitlistClass.get(0).getStudentID());
                                                statusLog += String.format("%s, %s %s has been scheduled into %s\n",
                                                                student.getLastName(),
                                                                student.getFirstName(), student.getStudentID(),
                                                                allWaitlistClass.get(0).getCourseCode());
                                        }
                                }
                        }

                }
                deleteStudentStatusText.setText(statusLog);
                updateSelectStudentComboBox();
        }// GEN-LAST:event_deleteStudentButtonActionPerformed

        private void displayClassesListButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_displayClassesListButtonActionPerformed
                // TODO add your handling code here:
                String semester = (String) currentSemesterComboBox.getSelectedItem();
                String courseCode = (String) selectDisplayClassCheckBox.getSelectedItem();
                DefaultTableModel modelScheduled = (DefaultTableModel) displayScheduleStudentTable.getModel();
                DefaultTableModel modelWaitlisted = (DefaultTableModel) displayScheduleWaitlistedTable.getModel();
                modelScheduled.setRowCount(0);
                modelWaitlisted.setRowCount(0);

                ArrayList<StudentEntry> scheduledResultSet = MultiTableQueries.getScheduledStudentsByClass(semester,
                                courseCode);
                ArrayList<StudentEntry> waitlistedResultSet = MultiTableQueries.getWaitlistedStudentsByClass(semester,
                                courseCode);

                for (StudentEntry rowEntry : scheduledResultSet) {
                        modelScheduled.addRow(
                                        new Object[] { rowEntry.getLastName(),
                                                        rowEntry.getFirstName(), rowEntry.getStudentID() });
                }

                for (StudentEntry rowEntry : waitlistedResultSet) {
                        modelWaitlisted.addRow(
                                        new Object[] { rowEntry.getLastName(),
                                                        rowEntry.getFirstName(), rowEntry.getStudentID() });
                }
        }// GEN-LAST:event_displayClassesListButtonActionPerformed

        private void selectDisplayClassCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_selectDisplayClassCheckBoxActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_selectDisplayClassCheckBoxActionPerformed

        private void updateScheduleTableButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_updateScheduleTableButtonActionPerformed
                // TODO add your handling code here:
                String semester = (String) currentSemesterComboBox.getSelectedItem();
                String studentID = StudentQueries.getStudentID((String) selectDisplayStudentCheckBox.getSelectedItem());
                DefaultTableModel model = (DefaultTableModel) displayScheduleTable.getModel();
                model.setRowCount(0);
                ArrayList<ScheduleEntry> resultSet = ScheduleQueries.getScheduleByStudent(semester, studentID);

                for (ScheduleEntry rowScheduleEntry : resultSet) {
                        model.addRow(
                                        new Object[] { rowScheduleEntry.getCourseCode(),
                                                        rowScheduleEntry.getStatus() });
                }

        }// GEN-LAST:event_updateScheduleTableButtonActionPerformed

        private void updateClassesTableActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_updateClassesTableActionPerformed
                String currentSemester = currentSemesterComboBox.getSelectedItem().toString();
                DefaultTableModel model = (DefaultTableModel) displayClassTable.getModel();
                model.setRowCount(0);
                ArrayList<ClassDescription> resultSet = MultiTableQueries.getAllClassDescriptions(currentSemester);

                for (ClassDescription rowClassDesc : resultSet) {
                        model.addRow(
                                        new Object[] { rowClassDesc.getCourseCode(),
                                                        rowClassDesc.getCourseDescription(),
                                                        rowClassDesc.getSeats() });
                }
        }// GEN-LAST:event_updateClassesTableActionPerformed

        private void addScheduleClassesButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_addScheduleClassesButtonActionPerformed
                // // TODO add your handling code here:
                String coursecode = (String) selectClassComboBox.getSelectedItem();
                String semester = (String) currentSemesterComboBox.getSelectedItem();
                String studentID = StudentQueries.getStudentID((String) selectStudentComboBox.getSelectedItem());
                Timestamp currentTimestamp = new Timestamp(Calendar.getInstance().getTime().getTime());

                int scheduledStudentCount = ScheduleQueries.getScheduledStudentCount(semester, coursecode);
                int seats = ClassQueries.getClassSeats(semester, coursecode);
                String status = "";
                if (seats > scheduledStudentCount) {
                        status = "Scheduled";
                        scheduleClassesStatusLabel.setText("Student scheduled successfully");
                } else {
                        status = "Waitlist";
                        scheduleClassesStatusLabel.setText("Student has been waitlisted");
                }

                ScheduleEntry newScheduleEntry = new ScheduleEntry(semester, coursecode, studentID, status,
                                currentTimestamp);
                ScheduleQueries.addScheduleEntry(newScheduleEntry);

        }// GEN-LAST:event_addScheduleClassesButtonActionPerformed

        private void changeSemesterButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_changeSemesterButtonActionPerformed
                updateAllComponents();
        }// GEN-LAST:event_changeSemesterButtonActionPerformed

        private void aboutButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_aboutButtonActionPerformed
                // TODO add your handling code here:
                // display about information.
                JOptionPane.showMessageDialog(null, "Author: " + "Daksh Mainee\n" + " Project: " + "Course Scheduler Fall 2024");
        }// GEN-LAST:event_aboutButtonActionPerformed

        private void addSemesterSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_addSemesterSubmitButtonActionPerformed
                String semester = addSemesterTextfield.getText();
                SemesterQueries.addSemester(semester);
                addSemesterStatusLabel.setText("Semester " + semester + " has been added.");
                rebuildSemesterComboBoxes();
        }// GEN-LAST:event_addSemesterSubmitButtonActionPerformed

        // ! No Implementation Needed
        private void courseCodeTextActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_courseCodeTextActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_courseCodeTextActionPerformed

        // ! No Implementation Needed
        private void courseDescTextActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_courseDescTextActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_courseDescTextActionPerformed

        private void addCourseButtonActionPerformed(java.awt.event.ActionEvent evt) {
                // TODO Error Check:
                String courseCode = courseCodeText.getText();
                String courseDesc = courseDescText.getText();
                CourseEntry newCourseEntry = new CourseEntry(courseCode, courseDesc);
                CourseQueries.addCourse(newCourseEntry);
                addCourseStatusLabel.setText("Added Course Successfuly");
                updateCourseComboBox();
        }// GEN-LAST:event_addCourseButtonActionPerformed

        private void addStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_addStudentButtonActionPerformed
                // TODO Error Check:
                String studentID = studentIDText.getText();
                String firstName = firstNameText.getText();
                String lastName = lastNameText.getText();
                StudentEntry newStudentEntry = new StudentEntry(studentID, firstName, lastName);
                StudentQueries.addStudent(newStudentEntry);
                addStudentStatusLabel.setText("Added Student Successfuly");
                updateSelectStudentComboBox();
        }// GEN-LAST:event_addStudentButtonActionPerformed

        private void addClassButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_addClassButtonActionPerformed
                // TODO Error Check: For sameCourseCode and Seat= 0"
                String courseCode = courseCodeComboBox.getSelectedItem().toString();
                String semester = currentSemesterComboBox.getSelectedItem().toString();
                int seats = (int) seatSpinner.getValue();
                ClassEntry newClassEntry = new ClassEntry(courseCode, semester, seats);
                ClassQueries.addClass(newClassEntry);
                addClassStatusLabel.setText("Added Class Successfuly");
                updateSelectClassComboBox();
        }// GEN-LAST:event_addClassButtonActionPerformed

        // ! No Implementation Needed
        private void studentIDTextActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_studentIDTextActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_studentIDTextActionPerformed

        // ! No Implementation Needed
        private void firstNameTextActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_firstNameTextActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_firstNameTextActionPerformed

        // ! No Implementation Needed
        private void lastNameTextActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_lastNameTextActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_lastNameTextActionPerformed

        private void checkData() {
                try {
                        FileReader reader = new FileReader("xzq789yy.txt");
                        BufferedReader breader = new BufferedReader(reader);

                        String encodedAuthor = breader.readLine();
                        String encodedProject = breader.readLine();
                        byte[] decodedAuthor = Base64.getDecoder().decode(encodedAuthor);
                        author = new String(decodedAuthor);
                        byte[] decodedProject = Base64.getDecoder().decode(encodedProject);
                        project = new String(decodedProject);
                        reader.close();

                } catch (FileNotFoundException e) {
                        // get user info and create file
                        author = JOptionPane.showInputDialog("Enter your first and last name.");
                        project = "Course Scheduler Fall 2023";

                        // write data to the data file.
                        try {
                                FileWriter writer = new FileWriter("xzq789yy.txt", true);
                                BufferedWriter bufferedWriter = new BufferedWriter(writer);

                                // encode the output data.
                                String encodedAuthor = Base64.getEncoder().encodeToString(author.getBytes());

                                bufferedWriter.write(encodedAuthor);
                                bufferedWriter.newLine();

                                String encodedProject = Base64.getEncoder().encodeToString(project.getBytes());
                                bufferedWriter.write(encodedProject);

                                bufferedWriter.close();
                        } catch (IOException ioe) {
                                ioe.printStackTrace();
                                System.exit(1);
                        }

                } catch (IOException e) {
                        e.printStackTrace();
                        System.exit(1);
                }

        }

        // #region Update Components
        private void updateAllComponents() {
                updateCourseComboBox();
                updateSelectClassComboBox();
                updateSelectStudentComboBox();
        }

        private void updateCourseComboBox() {
                ArrayList<String> currentCoursesList = CourseQueries.getAllCourseCodes();
                DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(
                                currentCoursesList.toArray(new String[0]));
                courseCodeComboBox.setModel(model);
        }

        private void updateSelectClassComboBox() {
                String currentSemester = currentSemesterComboBox.getSelectedItem().toString();
                ArrayList<String> semesterCourses = ClassQueries.getAllCourseCodes(currentSemester);
                DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(semesterCourses.toArray(new String[0]));
                selectClassComboBox.setModel(model);
                selectDisplayClassCheckBox.setModel(model);
                dropStudentClassComboBox.setModel(model);
                dropAdminClassComboBox.setModel(model);
        }

        private void updateSelectStudentComboBox() {
                ArrayList<StudentEntry> courses = StudentQueries.getAllStudents();

                String[] studentNames = new String[courses.size()];
                for (int i = 0; i < courses.size(); i++) {
                        StudentEntry student = courses.get(i);
                        String fullName = student.getLastName() + ", " + student.getFirstName();
                        studentNames[i] = fullName;
                }

                DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(studentNames);
                selectStudentComboBox.setModel(model);
                selectDisplayStudentCheckBox.setModel(model);
                deleteStudentComboBox.setModel(model);
                dropStudentClassStudentComboBox.setModel(model);
        }

        // #endregion

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(MainFrame.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(MainFrame.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(MainFrame.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(MainFrame.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new MainFrame().setVisible(true);
                        }
                });
        }

        // #region Components
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutButton;
    private javax.swing.JButton addClassButton;
    private javax.swing.JLabel addClassStatusLabel;
    private javax.swing.JButton addCourseButton;
    private javax.swing.JLabel addCourseStatusLabel;
    private javax.swing.JButton addScheduleClassesButton;
    private javax.swing.JLabel addSemesterStatusLabel;
    private javax.swing.JLabel addSemesterStatusLabel1;
    private javax.swing.JButton addSemesterSubmitButton;
    private javax.swing.JTextField addSemesterTextfield;
    private javax.swing.JButton addStudentButton;
    private javax.swing.JLabel addStudentStatusLabel;
    private javax.swing.JButton changeSemesterButton;
    private javax.swing.JLabel classCourseCodeLabel;
    private javax.swing.JComboBox<String> courseCodeComboBox;
    private javax.swing.JTextField courseCodeText;
    private javax.swing.JLabel courseCourseCodeLabel;
    private javax.swing.JLabel courseDescLabel;
    private javax.swing.JTextField courseDescText;
    private javax.swing.JComboBox<String> currentSemesterComboBox;
    private javax.swing.JLabel currentSemesterLabel;
    private javax.swing.JButton deleteStudentButton;
    private javax.swing.JComboBox<String> deleteStudentComboBox;
    private javax.swing.JLabel deleteStudentLabel;
    private javax.swing.JTextArea deleteStudentStatusText;
    private javax.swing.JTable displayClassTable;
    private javax.swing.JButton displayClassesListButton;
    private javax.swing.JTable displayScheduleStudentTable;
    private javax.swing.JTable displayScheduleTable;
    private javax.swing.JTable displayScheduleWaitlistedTable;
    private javax.swing.JButton dropAdminClassButton;
    private javax.swing.JComboBox<String> dropAdminClassComboBox;
    private javax.swing.JLabel dropAdminClassLabel;
    private javax.swing.JTextArea dropAdminClassLabelStatusText;
    private javax.swing.JButton dropStudentClassButton;
    private javax.swing.JComboBox<String> dropStudentClassComboBox;
    private javax.swing.JLabel dropStudentClassLabel;
    private javax.swing.JTextArea dropStudentClassStatusTextBox;
    private javax.swing.JComboBox<String> dropStudentClassStudentComboBox;
    private javax.swing.JLabel dropStudentStudentLabel;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameText;
    private javax.swing.JLabel scheduleClassesStatusLabel;
    private javax.swing.JLabel scheduledStudentsTableLabel;
    private javax.swing.JLabel seatLabel;
    private javax.swing.JSpinner seatSpinner;
    private javax.swing.JComboBox<String> selectClassComboBox;
    private javax.swing.JLabel selectClassLabel;
    private javax.swing.JLabel selectClassLabel1;
    private javax.swing.JComboBox<String> selectDisplayClassCheckBox;
    private javax.swing.JLabel selectDisplayClassLabel;
    private javax.swing.JComboBox<String> selectDisplayStudentCheckBox;
    private javax.swing.JComboBox<String> selectStudentComboBox;
    private javax.swing.JLabel selectStudentLabel;
    private javax.swing.JLabel studentIDLabel;
    private javax.swing.JTextField studentIDText;
    private javax.swing.JButton updateClassesTable;
    private javax.swing.JButton updateScheduleTableButton;
    private javax.swing.JLabel waitlistedStudentsTableLabel;
    // End of variables declaration//GEN-END:variables

        // #endregion
}
